name: DenHaag nightly scrape + tweets

on:
  schedule:
    - cron: '15 1 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper
        run: |
          python scraper.py
      - name: Build and (optionally) post tweets
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          DRY_RUN: ${{ secrets.DRY_RUN || '1' }}
        run: |
          python tweet_builder.py

name: DenHaag nightly scrape + tweets

on:
  schedule:
    # 01:15 UTC ≈ 03:15 Amsterdam (CEST). Pas aan in wintertijd indien gewenst.
    - cron: '15 1 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper
        run: |
          python scraper.py
      - name: Build and (optionally) post tweets
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          DRY_RUN: ${{ secrets.DRY_RUN || '1' }}
        run: |
          python tweet_builder.py
